# Generated by Django 5.0.2 on 2024-02-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firststate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course_1',
        ),
        migrations.RenameField(
            model_name='course_1',
            old_name='desc',
            new_name='description',
        ),
    ]
